name: GLITCH

on:
  push:
    branches: [ main ]
    
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v3
      with:
        source_repo: "https://github.com/deepgram-devs/talk-time-analytics.git"
        source_branch: "main"
        destination_repo: ${{ secrets.GLITCH_GIT_URL }}
        destination_branch: "main"
