# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v3
      with:
        source_repo: "https://github.com/deepgram/talk-time-analytics.git"
        source_branch: "master"
        destination_repo: ${{ secrets.GLITCH_GIT_URL }}
        destination_branch: "master"
